[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Introduction to Robotic"
authors = [{name = "Zhichao Liu", email = "zhichaol@uark.edu"}]
dynamic = ["version", "description"]
